apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  parameters:
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2d99b870-d2a7-48e4-9d8e-55a0ecf3bde0"
    keyvaultName: xg-uk-nonprod2-kv
    objects:  |
      array:
        - |
          objectName: shared-clusters-01-pg-admin-password
          objectType: secret       
    tenantId: 8b92eb99-dfa2-4bbe-ae8f-d6e66da44d6a
