---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus-community/kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus
  interval: 1m0s
  targetNamespace: monitoring
  install:
    createNamespace: true
