---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 2m0s
  url: https://prometheus-community.github.io/helm-charts
