---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dhos-medications-api
  namespace: flux-system
spec:
  chart:
    spec:
      chart: api/_by_installation/dhos-medications-api
      sourceRef:
        kind: GitRepository
        name: dhos-gdm
  interval: 1m0s
  targetNamespace: dhos-medications-api
  install:
    createNamespace: true
