---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dhos-medications-api
  namespace: flux-system
spec:
  chart:
    spec:
      chart: dhos-medications-api
      sourceRef:
        kind: HelmRepository
        name: dhos-gdm
  values:
    global:
      image:
        registry: humagdmacr.azurecr.io
  interval: 1m0s
  targetNamespace: dhos-medications-api
  install:
    createNamespace: true
