---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: redis2
  interval: 1m0s
  targetNamespace: redis2
  install:
    createNamespace: true

