---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dhos-medications-api
  namespace: flux-system
spec:
  chart:
    spec:
      chart: dhos-medications-api
      sourceRef:
        kind: HelmRepository
        name: dhos-gdm
  values:
    global:
      image:
        registry: humagdmacr.azurecr.io
      image_tag: dev
      db_host: xg-uk-nonprod2-01-cluster-db.postgres.database.azure.com
      db_password: test
      db_user_name: postgres
  dependsOn:
    - name:
        kube-prometheus
  interval: 1m0s
  targetNamespace: dhos-medications-api
  install:
    createNamespace: true
