apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - dhos-gdm-chart.yaml
  - dhos-medications-api-release.yaml

configMapGenerator:
  - name: values-cm
    files:
      - values.yaml
